harmony/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

harmony/harmony_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('menu/', include('shop.urls', namespace='shop')),
    path('reservation/', include('reservation.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

harmony/reservation/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('main/', views.room, name="main"),

    path('', views.createSimpleReservation, name="simple_reservation"),
    path('confirm/<str:pk>/', views.confirm_email, name="confirm_reservation"),
    path('delete/<str:pk>/', views.delete_reservation, name="delete_reservation"),
    path('email/', views.send_email, name="email_reservation"),
    # path('', views.createReservation, name="reservation"),

    path('holidays/', views.get_holidays, name="holidays"),
    path('create-holiday/', views.create_holiday, name="create-holiday"),

    path('day-details/<str:dt>/', views.DayDetailView, name="get_day"),
]

harmony/reservation/models.py
# from account.models import User
from django.db import models
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime    
# Create your models here.

"""Creating a simple reservation"""
class SimpleReservation(models.Model):
    fullname = models.CharField(max_length=200)
    user_email = models.EmailField(max_length=254, blank=True, null=True)
    # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(max_length=17, blank=True) # Validators should be a list (555) 555 - 5555
    reservation_date = models.CharField(max_length=15, blank=True, null=True)
    reservation_time = models.CharField(max_length=9, blank=True, null=True)
    confirmed = models.CharField(max_length=1, blank=True, null=True)
    num_of_people = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(8)], default=2)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.fullname + " Phone Number: " + self.phone_number + " Date: " + str(self.created)

"""Reservation day model represeting single day and free/non-free spots for that day"""
class ReservationDay(models.Model):
    date = models.DateField(null=False, blank=False)
    spots_total = models.IntegerField(null=True, default=32)
    spots_free = models.IntegerField(null=True, default=32)

    def __str__(self):
        return str(self.date) + " Total: " + str(self.spots_total) + " Free: " + str(self.spots_free)

"""Days that are free from work"""
class Holiday(models.Model):
    name = models.CharField(max_length=100, blank=True)
    date = models.DateField(null=False, blank=False)
    active = models.BooleanField(default=True, editable=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return str(self.name) + " " + str(self.date)


class DayTime1(models.Model):
    day = models.CharField(max_length=15)
    time = models.CharField(max_length=9)

harmony/reservation/forms.py
from django.forms import ModelForm
from django import forms
from .models import SimpleReservation, Holiday

class SimpleReservationForm(ModelForm):
    fullname = forms.CharField(label='Full name', max_length=100)
    user_email = forms.CharField(label='Email address',max_length=254)
    phone_number = forms.CharField(label='Phone Number',max_length=100)
    reservation_date = forms.CharField(label='Reservation Date')
    reservation_time = forms.CharField(label='Reservation Time')
    num_of_people = forms.IntegerField(label='Group Size')
    
    class Meta:
        model = SimpleReservation
        fields = ['fullname', 'user_email', 'phone_number', 'reservation_date', 'reservation_time', 'num_of_people']

# class SimpleReservationForm(ModelForm):
#     class Meta:
#         model = SimpleReservation
#         fields = ['fullname', 'phone_number', 'simple_reservation_date', 'num_of_people']

class HolidayForm(ModelForm):
    class Meta:
        model = Holiday
        fields = '__all__'

harmony/reservation/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import SimpleReservationForm, HolidayForm
import datetime
from itertools import chain
from django.shortcuts import get_object_or_404
##
import google
# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

import pickle
import os
from google_auth_oauthlib.flow import Flow, InstalledAppFlow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Create your views here.
def createSimpleReservation(request):
    """Users without an account and create a reservation"""
    form = SimpleReservationForm()
    max_group_size = 10
    options_group_size = max_group_size

    today = datetime.date.today()
    
    if request.method == 'POST':
        form = SimpleReservationForm(request.POST)
        if form.is_valid():
            reservation_date = form.cleaned_data['reservation_date']
            
            # check if the day is valid
            print('reservation date:::')
            print(reservation_date)
            res_date = datetime.datetime.strptime(reservation_date, "%Y-%m-%d").date()
            if res_date < today:
                return HttpResponse("You can not make reservations on days that have passed")

            # Check if it is not a holiday day
            if Holiday.objects.filter(date=reservation_date, active=True).count() != 0:
                return HttpResponse("You can not make reservations on holidays")

            # Check if spot is still available
            reservation_day = ReservationDay.objects.get_or_create(date=reservation_date)
            reservation_day = ReservationDay.objects.get(date=reservation_date)
            print('Reservation Day:')
            aa = reservation_day.spots_free
            print(aa)
            if reservation_day.spots_free < 1:
                return HttpResponse("No spots free or reservation closed")

            if reservation_day.spots_free < max_group_size:
                options_group_size = reservation_day.spots_free
            else:
                options_group_size = max_group_size
            # Decrement counter on Reservation Day
            reservation_day.spots_free = reservation_day.spots_free-1
            reservation_day.save()

            # Create reservation using current model
            reserv = form.save()

            #Send email for confirmation
            email_list = [
                reserv.user_email
            ]
            send_test_emails(email_list[0], reserv.created)
            return redirect('email_reservation')
        else:
            messages.error(request, 'An error occurred during registration')

    available_time = DayTime1.objects.filter(day='Saturday')
        
    context ={
        'form': form, 
        'today': today,
        'options_group_size': range(1, options_group_size+1),
        'available_time': available_time
        }
    return render(request, 'reservation/reservation_form.html', context)


def send_email(request):
    header = "An email has been sent!"
    body="Thank you for making a reservation! "
    message="Please follow the details on the email to confirm your reservation"
    context = {'header': header, 'body': body, 'message': message}
    return render(request, 'reservation/resevation_messages.html', context)


def confirm_email(request, pk):
    reserve= get_object_or_404(SimpleReservation, created=pk)
    if reserve.confirmed == 'Y':
        context = {'reserve': reserve}
        return render(request, 'reservation/confirm_reservation.html', context)
    
    
    time_now = datetime.datetime.now(tz=None)
    time_created = reserve.created.replace(tzinfo=None)
    
    dt = time_now - time_created

    if dt.seconds /60/60 > 19:
        reserve_date = reserve.reservation_date
        reserve_time = reserve.reservation_time
        header = "Your confirmation time has expired."
        body="Plase make a new reservation"
        message="Reservation date and time: " + str(reserve_date) + " " + str(reserve_time)
        context = {'header': header, 'body': body, 'message': message}
        return render(request, 'reservation/resevation_messages.html', context)

    reserve.confirmed = 'Y'
    reserve.save()
    context = {'reserve': reserve}
    return render(request, 'reservation/confirm_reservation.html', context)

def delete_reservation(request, pk):
    reserve = SimpleReservation.objects.get(created=pk)
    reserve_date = reserve.reservation_date
    reserve_time = reserve.reservation_time
    reserve.delete() 
    header = "Reservation Deleted Successfully!"
    body="Yor reservation with the following information has successfully been deleted"
    message="Reservation date and time: " + str(reserve_date) + " " + str(reserve_time)
    context = {'header': header, 'body': body, 'message': message}
    return render(request, 'reservation/resevation_messages.html', context)


@login_required(login_url='login')
def create_holiday(request):
    """Get holiday days in particular year"""
    form = HolidayForm()
    if request.user.is_superuser:
        if request.method == 'POST':
            form = HolidayForm(request.POST)
            if form.is_valid:
                form.save()
                """get the reservations for that date & send an SMS for the cancelation"""
                context={'form': form}
                return render(request, 'reservation/holiday_form.html', context)
    else:
        return HttpResponse('You are not allowed here!')

    context={'form': form}
    return render(request, 'reservation/holiday_form.html', context)


def get_holidays(request):
    """Get holiday days in particular year"""
    # date = int(request.GET['date'])
    # holidays = Holiday.objects.filter(
    #         date__gte=date,
    #         date__lte=date)
    holidays = Holiday.objects.all()
    context={'holidays': holidays}
    return render(request, 'reservation/holiday.html', context)


def DayDetailView(request, dt):
     """Get available spots for a day"""
     reserv_date = ReservationDay.objects.get(date=dt)
     context = {'reserv_date': reserv_date}
     return render(request, 'reservation/day_details.html', context)



def Create_Service(client_secret_file, api_name, api_version, *scopes):
    # print(client_secret_file, api_name, api_version, scopes, sep='-')
    SCOPES = [scope for scope in scopes[0]]
    # print(SCOPES)

    cred = None

    pickle_file = f'{api_name}_{api_version}.pickle'
    # print(pickle_file)

    if os.path.exists(pickle_file):
        with open(pickle_file, 'rb') as token:
            cred = pickle.load(token)

    if not cred or not cred.valid:
        if cred and cred.expired and cred.refresh_token:
            cred.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(client_secret_file, SCOPES)
            cred = flow.run_local_server()

        with open(pickle_file, 'wb') as token:
            pickle.dump(cred, token)

    try:
        service = build(api_name, api_version, credentials=cred)
        # print(API_SERVICE_NAME, 'service created successfully')
        return service
    except Exception as e:
        print('Unable to connect.')
        print(e)
        return None

def send_test_emails(email, id):
    CLIENT_SECRET_FILE = 'reservation/client_secret.json'
    API_NAME = 'gmail'
    API_VERSION = 'v1'
    SCOPES = ['https://mail.google.com/']

    service = Create_Service(CLIENT_SECRET_FILE, API_NAME, API_VERSION, SCOPES)
    
    email_body = '<p>Thank you for making a reservation with us.<br>To confirm your reservation please click <a href="http://127.0.0.1:8000/reservation/confirm/' + str(id) + '/" >here</a><br>Thanks,<br>Harmony Restaurant<br>202 17 Ave SE, Calgary, <br>AB T2G 1H4<br><a href="https://harmony-restaurant.ca/" >harmony-restaurant.ca<a></p>'

    # msg = MIMEText(email_body ,'html')

    emailMsg = email_body
    mimeMessage = MIMEMultipart()
    mimeMessage['to'] = email
    mimeMessage['subject'] = 'Confirm your reservation!'
    mimeMessage.attach(MIMEText(emailMsg, 'html'))
    raw_string = base64.urlsafe_b64encode(mimeMessage.as_bytes()).decode()

    message = service.users().messages().send(userId='me', body={'raw': raw_string}).execute()
    

harmony/reservation/templates/reservation/day_details.html
{% extends 'main_home.html' %}
{% block content %}
 {% include 'reservation/reservation_navbar.html'' %}
   <div>
        <h3>Day Details</h3>      

    </div>

{% endblock content %} 

harmony/reservation/templates/reservation/holiday.html
{% extends 'main_home.html' %}
{% block content %}
    <div>
 {% include 'reservation/reservation_navbar.html' %}
       <h3>Holidays</h3>
       <table id="holidays">
        <tr>
            <th>Holiday Name</th>
            <th>Date</th>
            <th>Is the restaurant open?</th>
          </tr>
            {% for holiday in holidays %}
            <tr>
                <td>{{holiday.name}}</td>
                <td>{{holiday.date}}</td>
                <td>{{holiday.active}}</td>
                <hr>
            </tr>
            {% endfor %}
            <!-- can add more detail in the the holiday(e.g. is the store closed)-->
        </table>
    </div>

{% endblock content %} 

harmony/reservation/templates/reservation/holiday_form.html
{% extends 'main_home.html' %}
{% block content %}
<h2>Hello {{request.user}}! </h2>
    <h3>Create a Holiday</h3>
    <div>
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <br>
            <div id="submit">
                <p><input  type="submit" value="Submit"></p>
            </div>
        </form>
    
    </div>

{% endblock content %} 

harmony/reservation/templates/reservation/reservation_form.html
{% extends 'main_home.html' %}
{% block content %}

  <div> 
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h3 class=" pb-1 mb-0 ruthie-font" style="color: #EB2328">Table Reservation</h3>
      <div>202 17 Ave SE, Calgary, AB T2G 1H4</div>
      <div>Tel No +1 (825) 438-4154</div>
    </div>
    <div class="stepper-horizontal" id="stepper1">
        <div class="step editing">
          <div class="step-circle"><span>1</span></div>
          <div class="step-title">Enter details</div>
          <div class="step-bar-left"></div>
          <div class="step-bar-right"></div>
        </div>
        <div class="step">
          <div class="step-circle"><span>2</span></div>
          <div class="step-title">Confirm</div>
          <div class="step-bar-left"></div>
          <div class="step-bar-right"></div>
        </div>
    </div>

    <div class="my-3 p-3 bg-body rounded shadow-sm" style="margin-right: 10%;">
      
  
      <form method="POST" action="">
        {% csrf_token %}
        <div class="form-row">
          
          <div class="col-md-4 mb-3 mx-auto text-center">
            <p class="Accent1" style="font-weight: 500">REGULAR <br>OPENING HOURS</p> 
          </div>
        
          <div class="col-md-4 mb-3">
            <label for="id_fullname">Full name:</label>
            <input type="text" name="fullname" maxlength="100" required="" id="id_fullname" class="form-control" >
          </div>

          <div class="col-md-4 mb-3">
            <label for="id_num_of_people">Group Size:</label>
            <select name="num_of_people" class="custom-select " id="id_num_of_people" required>
                {% for num in options_group_size %}
                  <option value="{{ num }}" >{{ num }}</option>
                {% endfor %}
            </select>
          </div>
          
        </div>
        
        <div class="form-row">
          
          <div class="col-md-4 mb-3 mx-auto text-center">
            <p >MONDAY - THURSDAY <br>4:00 PM – 12:00 AM</p>
          
          </div>

          <div class="col-md-4 mb-3">
              <label for="id_user_email">Email address:</label>
              <input type="text" name="user_email" maxlength="254" required="" id="id_user_email" class="form-control">
          </div>


          <div class="col-md-4 mb-3">
              <label for="id_phone_number">Phone Number:</label>
              <input type="text" name="phone_number" maxlength="100" required="" id="id_phone_number" class="form-control">
          </div>
        </div>

        <div class="form-row">

          <div class="col-md-4 mb-3 mx-auto text-center">
            <p >FRIDAY<br>4:00 PM – 2:00 AM</p>
            <p >SATURDAY<br>11:00 AM – 02:00 AM</p>
          </div>

          <div class="col-md-4 mb-3">
              <label for="id_reservation_date">Reservation Date:</label>
              <input class="form-control " name="reservation_date"  type="date" id="id_reservation_date" name="trip-start" value="{{ today|date:'Y-m-d' }}" min="{{ today|date:'Y-m-d' }}" max="2023-12-31">
          </div>


          <div class="col-md-4 mb-3">
              <label for="id_reservation_time">Reservation Time:</label>
              <select name="reservation_time" class="custom-select " id="id_reservation_time" required>
                  {% for hour in available_time %}
                      <option value="{{ hour.time }}">{{ hour.time }}</option>
                  {% endfor %}
              </select>
          </div>


          
        </div>
        <div class="form-row">
          <div class="col-md-4 mb-3 mx-auto text-center">
            <p class="">SUNDAY <br>11:00 AM – 12:00 AM</p>
          </div>

          <div class="col-md-8 mb-3 mx-auto text-center">
            <div class="submit">
              <p>
                <button class="btn Accent1-bg " type="submit" value="Submit">MAKE A RESERVATION</button>
              </p>
            </div>
          </div>

         
        </div>
        <br>
        
      </form>
    </div>
  </div>

  <script>
      const isNumericInput = (event) => {
      const key = event.keyCode;
      return ((key >= 48 && key <= 57) || // Allow number line
          (key >= 96 && key <= 105) // Allow number pad
      );
  };
  
  const isModifierKey = (event) => {
      const key = event.keyCode;
      return (event.shiftKey === true || key === 35 || key === 36) || // Allow Shift, Home, End
          (key === 8 || key === 9 || key === 13 || key === 46) || // Allow Backspace, Tab, Enter, Delete
          (key > 36 && key < 41) || // Allow left, up, right, down
          (
              // Allow Ctrl/Command + A,C,V,X,Z
              (event.ctrlKey === true || event.metaKey === true) &&
              (key === 65 || key === 67 || key === 86 || key === 88 || key === 90)
          )
  };
  
  const enforceFormat = (event) => {
      // Input must be of a valid number format or a modifier key, and not longer than ten digits
      if(!isNumericInput(event) && !isModifierKey(event)){
          event.preventDefault();
      }
  };
  
  const formatToPhone = (event) => {
      if(isModifierKey(event)) {return;}
  
      // I am lazy and don't like to type things more than once
      const target = event.target;
      const input = event.target.value.replace(/\D/g,'').substring(0,10); // First ten digits of input only
      const zip = input.substring(0,3);
      const middle = input.substring(3,6);
      const last = input.substring(6,10);
  
      if(input.length > 6){target.value = `(${zip}) ${middle} - ${last}`;}
      else if(input.length > 3){target.value = `(${zip}) ${middle}`;}
      else if(input.length > 0){target.value = `(${zip}`;}
  };
  /////////////////////////////////////////////////////////
  var currentStep = 1;
  var numSteps = 4;
  
  function nextStep() {
    currentStep++;
    if (currentStep > numSteps) {
      currentStep = 1;
    }
    var stepper = document.getElementById('stepper1');
    var steps = stepper.getElementsByClassName('step');
    
    Array.from(steps).forEach((step, index) => {
          let stepNum = index + 1;
      if (stepNum === currentStep) {
        addClass(step, 'editing');
      } else {
        removeClass(step, 'editing');
      }    
      if (stepNum < currentStep) {
        addClass(step, 'done');
      } else {
        removeClass(step, 'done');
      }
    })  
  }
  
  
  /* get, set class, see https://ultimatecourses.com/blog/javascript-hasclass-addclass-removeclass-toggleclass */
  
  function hasClass(elem, className) {
      return new RegExp(' ' + className + ' ').test(' ' + elem.className + ' ');
  }
  
  function addClass(elem, className) {
      if (!hasClass(elem, className)) {
          elem.className += ' ' + className;
      }
  }
  
  function removeClass(elem, className) {
      var newClass = ' ' + elem.className.replace( /[\t\r\n]/g, ' ') + ' ';
      if (hasClass(elem, className)) {
          while (newClass.indexOf(' ' + className + ' ') >= 0 ) {
              newClass = newClass.replace(' ' + className + ' ', ' ');
          }
          elem.className = newClass.replace(/^\s+|\s+$/g, '');
      }
  }

  ////
  const inputElement = document.getElementById('id_phone_number');
  inputElement.addEventListener('keydown',enforceFormat);
  inputElement.addEventListener('keyup',formatToPhone);
  </script>

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Ruthie&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Urbanist:wght@300;500&display=swap');
    body {
      background-color: rgb(0, 0, 0);
      color: #FFFDD7;
      font-family: 'Urbanist', sans-serif;
      font-weight: 300;
    }
    .ruthie-font {
      font-family: 'Ruthie', cursive;
      font-size: 4em;
    }
    .Accent1 {
      color: #F06A23;
    }
    .Accent1-bg {
      color: #FFFDD7;
      background-color: #F06A23;
    }

  .stepper-horizontal {
  display: table;
  width: 100%;
  margin: 0 auto;
}
.stepper-horizontal .step {
  display: table-cell;
  position: relative;
  padding: 1.5rem;
  z-index: 2;
  width: 25%;
}
.stepper-horizontal .step:last-child .step-bar-left, .stepper-horizontal .step:last-child .step-bar-right {
  display: none;
}
.stepper-horizontal .step .step-circle {
  width: 2rem;
  height: 2rem;
  margin: 0 auto;
  border-radius: 50%;
  text-align: center;
  line-height: 1.75rem;
  font-size: 1rem;
  font-weight: 600;
  z-index: 2;
  border: 2px solid #d9e2ec;
}
.stepper-horizontal .step.done .step-circle {
  background-color: #199473;
  border: 2px solid #199473;
  color: #ffffff;
}
.stepper-horizontal .step.done .step-circle:before {
  font-family: "FontAwesome";
  font-weight: 100;
  content: "";
}
.stepper-horizontal .step.done .step-circle * {
  display: none;
}
.stepper-horizontal .step.done .step-title {
  color: #102a43;
}
.stepper-horizontal .step.editing .step-circle {
  background: #ffffff;
  border-color: #199473;
  color: #199473;
}
.stepper-horizontal .step.editing .step-title {
  color: #199473;
}
.stepper-horizontal .step .step-title {
  margin-top: 1rem;
  font-size: 1rem;
  font-weight: 600;
}
.stepper-horizontal .step .step-title,
.stepper-horizontal .step .step-optional {
  text-align: center;
  color: #829ab1;
}
.stepper-horizontal .step .step-optional {
  font-size: 0.75rem;
  font-style: italic;
  color: #9fb3c8;
}
.stepper-horizontal .step .step-bar-left,
.stepper-horizontal .step .step-bar-right {
  position: absolute;
  top: calc(2rem + 5px);
  height: 5px;
  background-color: #d9e2ec;
  border: solid #d9e2ec;
  border-width: 2px 0;
}
.stepper-horizontal .step .step-bar-left {
  width: calc(100% - 2rem);
  left: 50%;
  margin-left: 1rem;
  z-index: -1;
}
.stepper-horizontal .step .step-bar-right {
  width: 0;
  left: 50%;
  margin-left: 1rem;
  z-index: -1;
  transition: width 500ms ease-in-out;
}
.stepper-horizontal .step.done .step-bar-right {
  background-color: #199473;
  border-color: #199473;
  z-index: 3;
  width: calc(100% - 2rem);
}
  </style>
{% endblock content %}

harmony/reservation/templates/reservation/resevation_messages.html
{% extends 'main_home.html' %}
{% load static %}
{% block content %}

<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h3 class=" fw-normal Primary">{{ header }}</h3>
    <p class="fs-5 text-muted">{{ body }}</p>
    <p class="fs-5 text-muted">{{ message }}</p>
  </div>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Ruthie&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Urbanist:wght@300;500&display=swap');
        body {
        background-color: rgb(0, 0, 0);
        color: white;
        font-family: 'Urbanist', sans-serif;
        font-weight: 500;
        }
        .ruthie-font {
        font-family: 'Ruthie', cursive;
        font-size: 4em;
        }
        .Primary {
            color: #EB2328;
        }
        .Accent1 {
        color: #F06A23;
        }
        .Accent1-bg {
        color: #FFFDD7;
        background-color: #F06A23;
        }
    </style>
{% endblock content %}